apiVersion: v1
kind: PersistentVolume
metadata:
  name: name
  labels:
    key: value
  namespace: name
spec:
  accessModes:
    - [ ReadWriteOnce | ReadOnlyMany | ReadWriteMany | ReadWriteOncePod ]
  capacity:
    storage: 1Gi
  storageClassName: name
  persistentVolumeReclaimPolicy: [ Retain | Delete | Recycle ]
  hostPath:
    path: "/mnt/data"
