apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secret-vlm
          mountPath: "/etc/secret-volume"
  volumes:
    - name: secret-vlm
      secret:
        secretName: my-secret
