apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
spec:
  containers:
    - name: admin-pod
      image: busybox:1.28
      command:
        - sh
        - -c
        - sleep 1000
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
