apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.19.1
        name: nginx
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap-volume
          mountPath: /etc/nginx
        - name: secret-volume
          mountPath: /etc/nginx/conf
      volumes:
      - name: configmap-volume
        configMap:
          name: nginx-config
      - name: secret-volume
        secret:
          secretName: nginx-htpasswd
status: {}