apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-to-port
spec:
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - port: 5000
    - from:
      - podSelector: {}
