apiVersion: networking.k8s.io/v1
kind: PolicyNetwork
metadata:
  name: deny-traffic-cross-namespace
  namespace: my-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {}
