apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: volumes-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-docroot
      volumes:
        - name: nginx-docroot
          persistentVolumeClaim:
            claimName: myclaim
