apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: volumes-test
spec:
  storageClassName: localpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi