apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    key: value
  namespace: name
spec:
  storageClassName: name
  accessModes:
  - [ ReadWriteOnce | ReadWriteMany | ReadOnlyMany | ReadWriteOncePod ]
  resources:
    requests:
      storage: 1Gi