apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
    name: backend
    pod-template-hash: 6c9b4bc88d
  name: backend
  namespace: ns-be
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: backend
status:
  loadBalancer: {}
