apiVersion: v1
kind: Pod
metadata:
  name: shipping-web
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: check-shipping-svc
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    command:
    - sh
    - -c
    - until nslookup shipping-svc; do echo waiting for shipping-svc; sleep 2; done